In [1]:
from gibbon.maps import MapSensor, TerrainMap, TerrainTile
import numpy as np
import json

In [2]:
origin = [113.256746, 23.115496]
radius = 2000

In [3]:
sensor = MapSensor(origin, radius)

In [4]:
tmaps = TerrainMap(sensor)

In [6]:
tensor_path = r'C:\Users\wenhs\Desktop\export\tensor.json'

In [5]:
tmaps.load_tensor(tensor_path)

NameError: name 'tensor_path' is not defined

In [7]:
tmaps.create_tiles()

HTTPSConnectionPool(host='api.mapbox.com', port=443): Max retries exceeded with url: /v4/mapbox.terrain-rgb/17/106770/56884@2x.png?access_token=sk.eyJ1IjoidmN0Y24iLCJhIjoiY2sxaDc4ZGllMGF0dTNpanlvOXdjNmVrNCJ9.ImJfE6k-f0aMzJj6vSHEYg (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
- connection exceeded limit at thread_count= 21
HTTPSConnectionPool(host='api.mapbox.com', port=443): Max retries exceeded with url: /v4/mapbox.terrain-rgb/17/106770/56883@2x.png?access_token=sk.eyJ1IjoidmN0Y24iLCJhIjoiY2sxaDc4ZGllMGF0dTNpanlvOXdjNmVrNCJ9.ImJfE6k-f0aMzJj6vSHEYg (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
- connection exceeded limit at thread_count= 21
HTTPSConnectionPool(host='api.mapbox.com', port=443): Max retries exceeded with url: /v4/mapbox.terrain-rgb/17/106768/56880@2x.png?access_token=sk.eyJ1IjoidmN0Y24iLCJhIjoiY2sxaDc4ZGllMGF0dTNpanlvOXdjNmVrNCJ9.ImJfE6k-f0aMzJj6vSHEYg (Caused by SSLError(SSLError("bad handshake

In [8]:
mesh_path = r'C:\Users\wenhs\Desktop\export\mesh.json'

In [9]:
tmaps.dump_mesh(mesh_path)

In [10]:
tmaps.dump_tensor(tensor_path)

In [10]:
len(tmaps._tiles[0][0].faces)

81

In [12]:
np.rot90(tmaps._tiles)

array([[<gibbon.maps._terrain_tile.TerrainTile object at 0x00000223D6D4D438>,
      dtype=object)

In [4]:
single_path = r'C:\Users\wenhs\Desktop\export\single.json'

In [5]:
with open(single_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

In [6]:
index = list(eval(list(data.keys())[0]))

In [7]:
center = sensor.center_index

In [8]:
index

[106677, 54786, 17]

In [8]:
matrix = list(data.values())[0]

In [9]:
sin = TerrainTile(center, index, matrix)

self._vertices_indices = [[[  0   0]
  [  0  56]
  [  0 113]
  [  0 170]
  [  0 227]
  [  0 283]
  [  0 340]
  [  0 397]
  [  0 454]
  [  0 511]]

 [[ 56   0]
  [ 56  56]
  [ 56 113]
  [ 56 170]
  [ 56 227]
  [ 56 283]
  [ 56 340]
  [ 56 397]
  [ 56 454]
  [ 56 511]]

 [[113   0]
  [113  56]
  [113 113]
  [113 170]
  [113 227]
  [113 283]
  [113 340]
  [113 397]
  [113 454]
  [113 511]]

 [[170   0]
  [170  56]
  [170 113]
  [170 170]
  [170 227]
  [170 283]
  [170 340]
  [170 397]
  [170 454]
  [170 511]]

 [[227   0]
  [227  56]
  [227 113]
  [227 170]
  [227 227]
  [227 283]
  [227 340]
  [227 397]
  [227 454]
  [227 511]]

 [[283   0]
  [283  56]
  [283 113]
  [283 170]
  [283 227]
  [283 283]
  [283 340]
  [283 397]
  [283 454]
  [283 511]]

 [[340   0]
  [340  56]
  [340 113]
  [340 170]
  [340 227]
  [340 283]
  [340 340]
  [340 397]
  [340 454]
  [340 511]]

 [[397   0]
  [397  56]
  [397 113]
  [397 170]
  [397 227]
  [397 283]
  [397 340]
  [397 397]
  [397 454]
  [397 511]]


In [10]:
sin.mesh

{'tp': 'mesh',
 'v': [[[746455.3451538086, -447873.20709228516, 31800.00000000109],
   [779176.6753523317, -447873.20709228516, 31500.0],
   [812482.3150186855, -447873.20709228516, 32600.000000000364],
   [845787.9546850395, -447873.20709228516, 33700.00000000073],
   [879093.5943513934, -447873.20709228516, 33300.00000000109],
   [911814.9245499165, -447873.20709228516, 32300.00000000109],
   [945120.5642162703, -447873.20709228516, 32200.000000000728],
   [978426.2038826243, -447873.20709228516, 32900.000000001455],
   [1011731.8435489782, -447873.20709228516, 32800.00000000109],
   [1045037.483215332, -447873.20709228516, 32400.000000001455]],
  [[746455.3451538086, -415151.87689376203, 34300.00000000109],
   [779176.6753523317, -415151.87689376203, 35200.00000000073],
   [812482.3150186855, -415151.87689376203, 36400.000000001455],
   [845787.9546850395, -415151.87689376203, 36200.00000000073],
   [879093.5943513934, -415151.87689376203, 34600.000000000364],
   [911814.9245499165,